import Head from "next/head";
import HeroSection from "components/HeroSection";

import AboutUs from "components/AboutUs";
import Article from "components/Article";
export default function Home() {
  return (
    <>
      <Head>
        <title>Food Blogging Website | TIF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full ">
        <HeroSection />
        <AboutUs />
        <Article />
      </main>
    </>
  );
}
